name: Build Windows MSI Installer

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (openjdk 17)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adoptopenjdk'
          java-version: '21'

      # Step 3: Install dependencies (e.g., jpackage, and other required tools)
      - name: Install dependencies
        run: |
          choco install openjdk21 jdk-installer

      # Step 4: Build the application (with jpackage to create the MSI file)
      - name: Build the MSI Installer
        run: |
          # Run jpackage to build the MSI installer
          jpackage --input target --name Pomodazzle \
            --main-jar Pomodazzle-1.0-SNAPSHOT-jar-with-dependencies.jar \
            --main-class com.porfanid.pomodazzle.Pomodazzle \
            --module-path "C:\JavaFX\javafx-sdk-17\lib" \
            --add-modules javafx.controls,javafx.fxml,javafx.web \
            --type msi \
            --dest ./package/Pomodazzle \
            --icon "icons\pomodazzle-icon.ico" \  # Specify app icon for the app and installer
            --win-shortcut \
            --win-menu \
            --win-per-user-install \
            --win-dir-chooser

      # Step 5: Upload the MSI as an artifact (so you can download it from GitHub)
      - name: Upload MSI file
        uses: actions/upload-artifact@v3
        with:
          name: pomodazzle-installer
          path: ./package/Pomodazzle/pomodazzle-*.msi
